# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
    - UserStory8233
  paths:
    include:
    - Source/UI/AccuVFrontend/POC/devexpress-material-ui-micro/*

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: CmdLine@2
  inputs:
    script: |
      echo Where am I?
      ls
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'
- script: |
    npm install
    npm run build-prd
  displayName: 'npm install and build'
  workingDirectory: ./Source/UI/AccuVFrontend/POC/devexpress-material-ui-micro/
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: './Source/UI/AccuVFrontend/POC/devexpress-material-ui-micro/build'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId)'
    replaceExistingArchive: true
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    ArtifactName: 'dropzip'
  displayName: "Publish artifact"

